---
- name: Configure all lab machines
  hosts: lab
  become: true
  roles:
    - common

- name: Configure web servers
  hosts: web
  become: true
  roles:
    - web

- name: Configure app servers
  hosts: app
  become: true
  roles:
    - app

- name: Configure misc servers
  hosts: misc
  become: true
  roles:
    - misc
